/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Fix export button and save": "修复导出按钮和保存",
    "ENABLED": "启用",
    "Export to file": "导出为文件",
    "Import clipboard": "从剪贴板导入",
    "Import file": "从文件导入",
    "DISABLED": "禁用",
    "Experience": "经验值",
    "Cancel": "取消",
    "HP:": "生命值:",
    "Help": "帮助",
    "Ice": "冰",
    "I want to mention that there are some features in this game that do not update in the background, and even more that don't update with offline progress. I want to sincerely apologize for this—I really did try to incorporate a function that would allow everything to update with background/offline progress, but nothing seemed to work perfectly. To make idle progress work to its fullest extent, I suggest keeping the game open in a background window.": "我想提一下，这款游戏中有一些功能不会在后台自动更新，甚至还有更多功能无法根据离线进度进行更新。对此我深感抱歉——我确实曾试图加入一个能让所有内容都能根据后台/离线进度进行更新的功能，但似乎都没有完全成功。为了使闲置进度能够充分发挥作用，我建议将游戏保持在后台窗口中运行。",
    "IMPORTANT NOTE: This game is unfortunately NOT compatible with mobile devices at this time. I say this now because, although the game can be started on mobile with limited issues, there will soon be a large feature unlocked that requires arrow keys and thus cannot be played on mobile. I am truly sorry for the incovenience, but if you have a PC or laptop, try playing the game there! I promise everything will run much more smoothly!": "重要提示：很遗憾，目前这款游戏无法在移动设备上运行。我提前说明这一点是因为，虽然可以在移动设备上启动这款游戏且存在一些限制性问题，但很快将会解锁一个大量功能，而这些功能需要使用方向键操作，因此无法在移动设备上进行游戏。对此给您带来的不便我深感抱歉，但如果您有台电脑或笔记本电脑，请尝试在那里玩这款游戏！我保证在那里运行会更加流畅！",
    "Fire": "火",
    "Level-Up Card": "升级卡牌",
    "Manual Save": "手动保存",
    "Normal": "正常",
    "Next ore:": "下一个矿石:",
    "Player": "玩家",
    "seconds)": "秒)",
    "Ruby": "红宝石",
    "Your Gems:": "你的宝石:",
    "You have defeated": "你被击败了",
    "You currently have": "你当前有",
    "Total gems gained:": "总计获得的 宝石:",
    "Total dirt gained:": "总计获得的 泥土:",
    "Total XP gained:": "总计获得的 经验值:",
    "Total spicy peppers gained:": "总计获得的 辛辣的辣椒:",
    "Total keys gained:": "总计获得的 钥匙:",
    "Total damage dealt:": "总计造成的伤害:",
    "Total cards opened:": "总计打开的卡牌:",
    "Total card level-ups:": "总计升级的卡牌:",
    "Total battle upgrades purchased:": "总计购买的战斗升级:",
    "Total mining upgrades purchased:": "总计购买的采矿升级:",
    "Total time played:": "总计游戏时长:",
    "Once starting, you may find that the game is REALLY slow, since you can only draw a card every hour and can't do much else besides that. This is intentional, and I promise there are a lot more features to come! This was meant to be the kind of game where you don't need to be too active, and it wouldn't take up too much of a player's time.": "一旦开始游戏，你可能会发现它的运行速度非常慢，因为每小时你只能抽取一张牌，除此之外几乎无法进行其他操作。这是有意为之的，我保证后续还会有更多的功能推出！这是为了打造一种不需要玩家过于活跃的游戏类型，而且也不会占用玩家太多的时间。",
    "New Features?!": "新功能?!",
    "New Best Friend": "新最佳好友",
    "Offline progress": "离线进度",
    "Thank you so much for checking out my game! What you're about to see is the culmination of weeks of dedication to create my first actual idle/incremental game. This is something I've always wanted to do, and it means a lot to me that it's finally a reality.": "",
    "Thank you so much for checking out my game! What you're about to see is the culmination of weeks of dedication to create my first actual idle/incremental game. This is something I've always wanted to do, and it means a lot to me that it's finally a reality.": "非常感谢您玩我的游戏！接下来您将看到的是我花费数周时间精心制作的第一款真正意义上的放置/渐进式游戏的成果。这是我一直以来的梦想，它终于成真了，对我来说意义非凡。",
    "As previously mentioned, this is my first ever real game! That being said, it is more than likely that there are some bugs or inaccuracies that could occur while playing normally. If you catch anything, please let me know on Galaxy or through the Discord, and I will try my best to resolve the issue!": "如前所述，这是我人生中第一次真正参与的游戏！话虽如此，但在正常游玩过程中，很有可能会出现一些漏洞或错误。如果您发现了任何问题，请在“Galaxy”平台或通过“Discord”渠道告知我，我会尽力解决这个问题！",
    "Unlock all cards": "解锁所有卡牌",
    "Teleport!": "传送!",
    "That Was Simple": "那很简单",
    "The Shiny...": "闪光...",
    "Teleport to depth:": "传送到深度:",
    "These Are Heavy...": "这些太重了...",
    "Stats": "统计",
    "Mining": "采矿",
    "Larger Tanks": "非常感谢",
    "Game Saved!": "游戏已保存!",
    "Freeze:": "冻结:",
    "Freeze Chance:": "冻结几率:",
    "Fight Dragon": "对抗巨龙",
    "Enter the Game!": "进入游戏!",
    "Settings/Stats": "设置/统计",
    "Return to the surface first time": "首次返回地面",
    "Return to Surface resets mined cells and your max depth reached, turns the autominer inactive, and returns you to the bubble row. You can do this once every 8 hours.": "返回到地面将重置挖掘的单元格和达到的最大深度，将自动器变为非活动状态，并返回到气泡行。此操作每 8 小时可执行一次。",
    "Poison Chance:": "中毒几率:",
    "Return to Surface": "返回地面",
    "Poison:": "中毒:",
    "Poison": "毒",
    "(maxed)": "(满级)",
    "— Poison damage percent": "— 中毒伤害百分比",
    "— Multiplier to HP": "— 乘数到生命值",
    "— Multiplier to Damage": "— 乘数到伤害",
    "— Mana regeneration": "— 法力回复",
    "— Mana storage": "— 法力存储",
    "— Chance to block projectiles": "— 格挡投掷物的几率",
    "— Lower dragon scaling exponent": "— 更低的巨龙缩放指数",
    "— Freeze duration": "— 冻结持续时长",
    "— Increase dirt gain": "— 提高泥土增益",
    "— Increase key chance": "— 提高钥匙几率",
    "— Increase mining speed": "— 提高采矿速度",
    "Cards": "卡牌",
    "Cards unlocked:": "已解锁卡牌:",
    "cards at once": "卡牌一次性",
    "Choose weapon:": "选择武器:",
    "Claim": "领取",
    "Century-Old Story": "百年往事",
    "Card Collector": "卡牌收藏家",
    "California Ghost": "加州幽灵",
    "Block Chance": "格挡几率",
    "Billionaire": "亿万富翁",
    "Better Value": "更优价值",
    "Battle Upgrades": "战斗升级",
    "Damage:": "伤害:",
    "Bubble": "气泡",
    "Dirt": "泥土",
    "Defeat your first dragon": "击败你的第一条巨龙",
    "Dracremental": "抽卡增量",
    "Dragon": "龙",
    "Discover all gems": "发现所有宝石",
    "Disable AI images": "禁用AI图像",
    "Welcome to Dracremental!": "欢迎来到抽卡增量!",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "???": "???",
    "▶": "▶",
    "◀": "◀",
    "--": "--",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "@": "@",
    "^": "^",
    "&": "&",
    "%": "%",
    "--": "--",
    "=": "=",
    "?": "?",
    "!": "!",
    "$": "$",
    "#": "#",
    "/": "/",
    "]": "]",
    "[": "[",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Gityx游戏': 'Gityx游戏',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "Mana: ": "法力: ",
    "Next level in ": "到下一级还要 ",
    "Time left: ": "剩余时间: ",
    "Start scientific notation at: ": "科学记数法开始于：",
    "(starting at depth ": "(开始于深度 ",
    "Autosave Interval: ": "自动保存间隔: ",
    "Depth: ": "深度: ",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    " XP/sec": " 经验值/秒",
    "\n": "\n",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^→ ([\d\.]+)$/,
    /^→ ([\d\.]+)\%$/,
    /^→ \^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^\(([\d\.]+), ([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^\+([\d\.]+)\%$/,
    /^\-([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^\(([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),\-([\d\.]+)\)$/,
    /^\(([\d\.]+),\-([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^\[([\d\.]+):([\d\.]+):([\d\.]+)\]$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)×$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^\/([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) dirt$/, '你有 $1 泥土'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^([\d\.]+)\/s$/, '$1\/秒'],
    [/^\(\+([\d\.]+)\/s\)$/, '(+$1\/秒)'],
    [/^([\d\.,]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^→ ([\d\.]+)\% key chance$/, '→ $1% 钥匙几率'],
    [/^→ ([\d\.]+)\% of damage\/sec$/, '→ $1% 伤害/秒'],
    [/^→ ([\d\.]+)× HP$/, '→ $1× 生命值'],
    [/^→ ([\d\.]+)× damage$/, '→ $1× 伤害'],
    [/^→ ([\d\.]+)× dirt$/, '→ $1× 泥土'],
    [/^→ ([\d\.]+)× speed$/, '→ $1× 速度'],
    [/^→ ([\d\.]+) seconds$/, '→ $1 秒'],
    [/^→ ([\d\.]+) mana$/, '→ $1 法力'],
    [/^→ ([\d\.]+) mana\/sec$/, '→ $1 法力/秒'],
    [/^\+([\d\.]+) elves$/, '+$1 精灵'],
    [/^\+([\d\.]+)\% elves$/, '+$1% 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)d ([\d\.]+):([\d\.]+):([\d\.]+)$/, '$1天 $2:$3:$4'],
    [/^([\d\.]+)h ([\d\.]+)m$/, '$1小时 $2分'],
    [/^([\d\.]+)m ([\d\.]+)s$/, '$1分钟 $2秒'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^\+([\d\.,]+) elves$/, '+$1 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^Autosave in: ([\d\.,]+)s$/, '自动保存: $1秒'],
    [/^Level ([\d\.,]+)$/, '等级 $1'],
    [/^Dragon Level ([\d\.,]+)$/, '巨龙 等级 $1'],
    [/^Player([\d\.,]+) Level ([\d\.,]+)$/, '玩家$1 等级 $2'],
    [/^Reach depth ([\d\.,]+)$/, '达到深度 $1'],
    [/^Reach Level ([\d\.,]+)$/, '达到等级 $1'],
    [/^Draw ([\d\.,]+) card for 1 key$/, '抽取 $1 卡牌 花费 $2 钥匙'],
    [/^Draw ([\d\.,]+) cards for 1 keys$/, '抽取 $1 卡牌 花费 $2 钥匙'],
    [/^Draw ([\d\.,]+) total cards$/, '总计抽取 $1 卡牌'],
    [/^Defeat ([\d\.,]+) dragons$/, '击败 $1 巨龙'],
    [/^Select ([\d\.,]+) Card$/, '选择 $1 卡牌'],
    [/^Select ([\d\.,]+) Cards$/, '选择 $1 卡牌'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^([\d\.,]+) \/ ([\d\.,]+) XP$/, '$1 \/ $2 经验值'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Effect: (.+) mana\/sec$/, '效果：$1 法力/秒'],
    [/^Effect: (.+) of damage\/sec$/, '效果：$1 伤害/秒'],
    [/^Effect: (.+) mana$/, '效果：$1 法力'],
    [/^Effect: (.+) seconds$/, '效果：$1 秒'],
    [/^Effect: (.+)× speed$/, '效果：$1× 速度'],
    [/^Effect: (.+)× HP$/, '效果：$1× 生命值'],
    [/^Effect: (.+)× dirt$/, '效果：$1× 泥土'],
    [/^Effect: (.+)× damage$/, '效果：$1× 伤害'],
    [/^Effect: (.+)$/, '效果：$1'],
    [/^Cost: (.+) Dirt$/, '成本：$1 泥土'],
    [/^Cost: (.+) Spicy Peppers$/, '成本：$1 辛辣的辣椒'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);